# This is a basic workflow to help you get started with Actions

name: CI
env:
  REPOSITORY: myinittest.azurecr.io
  IMAGE: icap-test
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ update/workflow ]
    paths-ignore: 
      - 'Documentation/**'
  pull_request:
    branches: [ update/workflow ]
    paths-ignore: 
      - 'Documentation/**'    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  build-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GW_SDK_TOKEN }} 
        submodules: true

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REPOSITORY }} # default: index.docker.io
        username: ${{ secrets.AZURE_USER }} 
        password: ${{ secrets.AZURE_PASS }} 

    - run: |
        docker build . -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
        docker push ${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
