# This is a basic workflow to help you get started with Actions

name: CI
env:
  REPOSITORY: glasswallicap58de6aa8.azurecr.io
  IMAGE: icap-test
  RESOURCE_GROUP: gw-icap-performance-pool-c11c167a
  FQDN1: icapdns1
  FQDN2: icapdns2
  FQDN3: icapdns3
  FQDN4: icapdns4
  FQDN5: icapdns5
  CONTAINER_NAME1: glasswallicap-1-c548cd81
  CONTAINER_NAME2: glasswallicap-2-e9e36fb4 
  CONTAINER_NAME3: glasswallicap-3-865d94a9 
  CONTAINER_NAME4: glasswallicap-4-79dffe96
  CONTAINER_NAME5: glasswallicap-5-5faa350b
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'Documentation/**'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'Documentation/**'    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  build-and-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GW_SDK_TOKEN }} 
        submodules: true

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REPOSITORY }} # default: index.docker.io
        username: ${{ secrets.REGISTRY_USER_2 }} 
        password: ${{ secrets.REGISTRY_PASS_2 }} 

    - run: |
        docker build . -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
        docker push ${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
        az container delete --name ${{ env.CONTAINER_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --yes || true  

    # Deploy the ICAP container to Azure container instances using the recent build image in Azure container registry 
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        dns-name-label: ${{ env.FQDN1 }}
        image: ${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
        ports: 1344
        registry-login-server: ${{ env.REPOSITORY }}
        registry-username: ${{ secrets.REGISTRY_USER_2 }}
        registry-password: ${{ secrets.REGISTRY_PASS_2 }}
        name: ${{ env.CONTAINER_NAME1 }}
        location: 'UK South'

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        dns-name-label: ${{ env.FQDN2 }}
        image: ${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
        ports: 1344
        registry-login-server: ${{ env.REPOSITORY }}
        registry-username: ${{ secrets.REGISTRY_USER_2 }}
        registry-password: ${{ secrets.REGISTRY_PASS_2 }}
        name: ${{ env.CONTAINER_NAME2 }}
        location: 'UK South'

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        dns-name-label: ${{ env.FQDN3 }}
        image: ${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
        ports: 1344
        registry-login-server: ${{ env.REPOSITORY }}
        registry-username: ${{ secrets.REGISTRY_USER_2 }}
        registry-password: ${{ secrets.REGISTRY_PASS_2 }}
        name: ${{ env.CONTAINER_NAME3 }}
        location: 'UK South'

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        dns-name-label: ${{ env.FQDN4 }}
        image: ${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
        ports: 1344
        registry-login-server: ${{ env.REPOSITORY }}
        registry-username: ${{ secrets.REGISTRY_USER_2 }}
        registry-password: ${{ secrets.REGISTRY_PASS_2 }}
        name: ${{ env.CONTAINER_NAME4 }}
        location: 'UK South'
        
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        dns-name-label: ${{ env.FQDN5 }}
        image: ${{ env.REPOSITORY }}/${{ env.IMAGE}}:${{ github.sha }}
        ports: 1344
        registry-login-server: ${{ env.REPOSITORY }}
        registry-username: ${{ secrets.REGISTRY_USER_2 }}
        registry-password: ${{ secrets.REGISTRY_PASS_2 }}
        name: ${{ env.CONTAINER_NAME5 }}
        location: 'UK South'
